# SPDX-FileCopyrightText: 2024 Bergrübe
# SPDX-FileCopyrightText: 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Inject a message about the the role being in maintenance mode on version 1
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "NOTE: This role is in maintenance mode. While Stirling PDF itself continues to be actively developed, this role is configured to install version 1 (" + stirling_pdf_version + ") and will not support version 2, because it enforces Open Core license since v2.0.0.

          Consider using one of the following free alternatives instead:
          - ansible-role-bentopdf: https://radicle.network/nodes/seed.radicle.garden/rad%3Az2bgVhWju6shYSwtdKb7v3eoSL1Pt
          - ansible-role-omnitools: https://github.com/mother-of-all-self-hosting/ansible-role-omnitools

          For an Ansible playbook which integrates those roles, see the Mother-of-All-Self-Hosting Ansible playbook: https://github.com/mother-of-all-self-hosting/mash-playbook

          You can suppress this warning by setting `stirling_pdf_show_warning` to `false`"
        ]
      }}
  when: "stirling_pdf_show_warning"

- name: Ensure stirling_pdf network is created in Docker
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ stirling_pdf_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"


- name: Ensure stirling_pdf path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0700"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
  with_items:
    - {path: "{{ stirling_pdf_base_path }}", when: true}
    - {path: "{{ stirling_pdf_config_path }}", when: true}

- name: Ensure stirling_pdf data, log and trainingData path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
  with_items:
    - {path: "{{ stirling_pdf_data_path }}", when: true}
    - {path: "{{ stirling_pdf_trainingData_path }}", when: true}
    - {path: "{{ stirling_pdf_logs_path }}", when: true}
    - {path: "{{ stirling_pdf_data_path }}/config", when: true}
    - {path: "{{ stirling_pdf_data_path }}/customFiles", when: true}
    - {path: "{{ stirling_pdf_data_path }}/pipeline", when: true}


- name: Ensure stirling_pdf traefik labels are installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ stirling_pdf_config_path }}/labels"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
    mode: "0640"

- name: Ensure stirling_pdf configuration is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ stirling_pdf_config_path }}/env"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
    mode: "0640"

- name: Ensure stirling_pdf extra config is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/extra_config.j2"
    dest: "{{ stirling_pdf_data_path }}/config/settings.yml"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
    mode: "0660"

- name: Ensure stirling_pdf container image is pulled
  community.docker.docker_image:
    name: "{{ stirling_pdf_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure stirling_pdf.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/stirling_pdf.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ stirling_pdf_identifier }}.service"
    mode: "0644"
