# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Bergrübe
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Inject a message about the the role being in maintenance mode on version 1
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "NOTE: This role is in maintenance mode. While Stirling PDF itself continues to be actively developed, this role is configured to install version 1 (" + stirling_pdf_version + ") and will not support version 2, because it enforces Open Core license since v2.0.0.

          Consider using one of the following free alternatives instead:
          - ansible-role-bentopdf: https://radicle.network/nodes/seed.radicle.garden/rad%3Az2bgVhWju6shYSwtdKb7v3eoSL1Pt
          - ansible-role-omnitools: https://github.com/mother-of-all-self-hosting/ansible-role-omnitools

          For an Ansible playbook which integrates those roles, see the Mother-of-All-Self-Hosting Ansible playbook: https://github.com/mother-of-all-self-hosting/mash-playbook

          You can suppress this warning by setting `stirling_pdf_show_warning` to `false`"
        ]
      }}
  when: "stirling_pdf_show_warning"

- name: Ensure Stirling PDF path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
  with_items:
    - "{{ stirling_pdf_base_path }}"

- name: Ensure Stirling PDF data paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
  with_items:
    - "{{ stirling_pdf_data_path }}"
    - "{{ stirling_pdf_trainingdata_path }}"
    - "{{ stirling_pdf_logs_path }}"
    - "{{ stirling_pdf_data_path }}/config"
    - "{{ stirling_pdf_data_path }}/customFiles"
    - "{{ stirling_pdf_data_path }}/pipeline"

- name: Ensure Stirling PDF support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ stirling_pdf_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
  with_items:
    - env
    - labels
  register: stirling_pdf_support_files_result

- name: Ensure Stirling PDF extra config is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/extra_config.j2"
    dest: "{{ stirling_pdf_data_path }}/config/settings.yml"
    owner: "{{ stirling_pdf_uid }}"
    group: "{{ stirling_pdf_gid }}"
    mode: "0660"

- name: Ensure Stirling PDF container image is pulled via community.docker.docker_image_pull
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image_pull:
    name: "{{ stirling_pdf_container_image }}"
    pull: always
  register: stirling_pdf_container_image_pull_result_ansible_module
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: stirling_pdf_container_image_pull_result_ansible_module is not failed

- name: Ensure Stirling PDF container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ stirling_pdf_container_image }}"
  register: stirling_pdf_container_image_pull_result_command
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: stirling_pdf_container_image_pull_result_command is not failed
  changed_when: "'Downloaded newer image' in stirling_pdf_container_image_pull_result_command.stdout"

- name: Ensure Stirling PDF container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ stirling_pdf_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: stirling_pdf_network_creation_result

- name: Ensure Stirling PDF container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ stirling_pdf_container_network }}
  register: stirling_pdf_network_creation_result
  changed_when: stirling_pdf_network_creation_result.rc == 0
  failed_when: stirling_pdf_network_creation_result.rc != 0 and 'already exists' not in stirling_pdf_network_creation_result.stderr

- name: Ensure Stirling PDF systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/stirling-pdf.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ stirling_pdf_identifier }}.service"
    mode: "0644"
  register: stirling_pdf_systemd_service_result

- name: Determine whether Stirling PDF needs a restart
  ansible.builtin.set_fact:
    stirling_pdf_restart_necessary: >-
      {{
        stirling_pdf_support_files_result.changed | default(false)
        or stirling_pdf_systemd_service_result.changed | default(false)
        or stirling_pdf_container_image_pull_result_ansible_module.changed | default(false)
        or stirling_pdf_container_image_pull_result_command.changed | default(false)
      }}
