# SPDX-FileCopyrightText: 2024 Bergrübe
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Validate and install stirling_pdf if enabled
  when: stirling_pdf_enabled | bool
  tags:
    - setup-all
    - setup-stirling-pdf
    - install-all
    - install-stirling-pdf
  block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Uninstall stirling_pdf if not enabled
  when: not stirling_pdf_enabled | bool
  tags:
    - setup-all
    - setup-stirling-pdf
  block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
