# SPDX-FileCopyrightText: 2024 Bergrübe
# SPDX-FileCopyrightText: 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of Stirling PDF systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ stirling_pdf_identifier }}.service"
  register: stirling_pdf_service_stat

- name: Uninstall Stirling PDF systemd services and files
  when: stirling_pdf_service_stat.stat.exists | bool
  block:
    - name: Ensure Stirling PDF service is stopped
      ansible.builtin.service:
        name: "{{ stirling_pdf_identifier }}"
        state: stopped
        daemon_reload: true
    - name: Ensure Stirling PDF service doesn't exist
      ansible.builtin.file:
        dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ stirling_pdf_identifier }}.service"
        state: absent

    - name: Ensure Stirling PDF base path is files deleted (make sure to delete node data)
      ansible.builtin.file:
        path: "{{ stirling_pdf_base_path }}"
        state: absent
