# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Bergrübe
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Stirling PDF systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ stirling_pdf_identifier }}.service"
  register: stirling_pdf_service_stat

- name: Uninstall Stirling PDF systemd services and files
  when: stirling_pdf_service_stat.stat.exists | bool
  block:
    - name: Ensure Stirling PDF systemd service is stopped
      ansible.builtin.service:
        name: "{{ stirling_pdf_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Stirling PDF systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ stirling_pdf_identifier }}.service"
        state: absent

    - name: Ensure Stirling PDF support files do not exist
      ansible.builtin.file:
        path: "{{ stirling_pdf_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Stirling PDF local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ stirling_pdf_data_path }}"
      register: stirling_pdf_data_path_deletion_result
      changed_when: stirling_pdf_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Stirling PDF base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ stirling_pdf_base_path }}"
      register: stirling_pdf_base_path_deletion_result
      changed_when: stirling_pdf_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Stirling PDF container network does not exist
      when: stirling_pdf_container_network_deletion_enabled
      block:
        - name: Ensure Stirling PDF container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ stirling_pdf_container_network }}"
            state: absent
          register: stirling_pdf_network_deletion_result

        - name: Ensure Stirling PDF container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ stirling_pdf_container_network }}
          register: stirling_pdf_network_deletion_result
          changed_when: stirling_pdf_container_network in stirling_pdf_network_deletion_result.stdout

- name: Check existence of Stirling PDF local data path
  ansible.builtin.stat:
    path: "{{ stirling_pdf_data_path }}"
  register: stirling_pdf_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Inject the message about the remaining Stirling PDF local data path
  when: stirling_pdf_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Stirling PDF instance has been removed, some old data remains in `" + stirling_pdf_data_path + "`. Feel free to delete it."
        ]
      }}
